### ISSUE TITLE
Demo with SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by nobodyiam** [kaelzhang/ctrip-apollo#3]
I installed node v11.6.0 and tried to run the demo as below, but got the error message: `SyntaxError: await is only valid in async function`, which looks like something's missing...

Test Code: 
```javascript
const apollo = require('ctrip-apollo')

const app = apollo({
  host: 'http://106.12.25.204:8080',
  appId: '100004458'
})

// Get the default namespace
const namespace = app.namespace()
// Namespace is an EventEmitter of nodejs
.on('change', ({
  key,
  oldValue,
  newValue
}) => {
  // Updates new values to `process.env`
  process.env[key] = newValue
})

// - Fetch configurations for the first time
// - start update notification polling (by default)
await namespace.ready()

console.log(namespace.get('timeout'))
```

Error Message: 
```javascript
await namespace.ready()
^^^^^

SyntaxError: await is only valid in async function
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
```

**Comment by kaelzhang** [comment]
As the error message indicates, `await` is only valid in async function, which is a new syntax of JavaScript.

```js
const start = async () => {
  await namespace.ready()
  console.log(namespace.get('timeout'))
}

start()
```

But many nodejs opensource projects just put await statements inside no async functions in example codes for simplicity.

However, the README.md has been improved for this issue.

**Comment by nobodyiam** [comment]
Thanks @kaelzhang for contributing such a powerful nodejs implementation of apollo-client! 

A link to this project is added in [apollo client third-party reference implementations](https://github.com/ctripcorp/apollo/wiki/Go%E3%80%81Python%E3%80%81NodeJS%E3%80%81PHP%E7%AD%89%E5%AE%A2%E6%88%B7%E7%AB%AF%E4%BD%BF%E7%94%A8%E6%8C%87%E5%8D%97)

**Comment by kaelzhang** [comment]
@nobodyiam Thanks buddy. `ctrip-apollo` is now fully tested

**Comment by nobodyiam** [comment]
great!
