### ISSUE TITLE
const {DEFAULT_POLLING_RETRY_POLICY} = require('./polling') DEFAULT_POLLING_RETRY_POLICY值为undefined。为什么要使用呢？

### ISSUE THREAD

**Issue by xiaokeqi** [kaelzhang/ctrip-apollo#6]
const {DEFAULT_POLLING_RETRY_POLICY} = require('./polling') DEFAULT_POLLING_RETRY_POLICY值为undefined。为什么要使用呢？

**Comment by kaelzhang** [comment]
Nice catch, buddy ~
